# Site settings
title:       "Code, Eat, Run, Lift"
email:       "tploskinajr@gmail.com"
author:      "Tom Ploskina Jr."
description: "A semi-weekly blog about my favorite topics"
baseurl:     ""
url:         "https://tmpjr.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: tmpjrme

# Social icons
github_username: tmpjr
stackoverflow_id: "hines-bourne"
twitter_username: tmpjrdotme
google_plus_id:
linkedin_username: tmpjr
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
