# Site settings
title:       Code, Eat, Run, Lift
email:       tploskinajr@gmail.com
author:      Tom Ploskina Jr.
description: "A semi-weekly blog about my favorite topics"
baseurl:     ""
url:         "http://tmpjr.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:tmpjr
stackoverflow_id:hines-bourne
twitter_username:tmpjrdotme
google_plus_id:
linkedin_username:tmpjr
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
